---
- name: Get scraper_dir
  shell: echo "$(git rev-parse --show-toplevel)/jobs_scaper"
  register: scraper_dir

- name: "Build"
  shell: cd {{scraper_dir.stdout}} && go build -o ./scraper
  environment:
    - GOARCH: arm
    - GOOS: linux
    - GOARM: 5

- name: Template a file to /etc/file.conf
  ansible.builtin.template:
    src: /scraper.service.j2
    dest: /etc/file.conf
    owner: bin
    group: wheel
    mode: '0644'
