---
- name: Get scraper_dir
  shell: echo "$(git rev-parse --show-toplevel)/jobs_scaper/entrypoints/sqs_worker"
  register: scraper_dir

- name: "Build"
  shell: cd {{scraper_dir.stdout}} && go build -o ./scraper
  environment:
    - GOARCH: arm
    - GOOS: linux
    - GOARM: 5




