namespace Jobs.Aggregator.Core
{
    public enum TechnologiesEnum
    {
        Java,
        Dotnet,
        Nodejs,
        Vuejs,
        React,
        Angular,
        Golang,
        Php,
        Cpp,
        C,
        Devops,
        Cloud,
        Embedded,
        Android,
        Ios,
        Arduino,
        Tensorflow,
        Javascript,
        Typescript,
        Python,
        Hardware,
        Iot,
        Sql,
        PlSql,
        TSql,
        Aws,
        Gcp,
        Azure,
        Jenkins,
        Teamcity,
        Symfony,
        Laravel
    }

}