name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: playbooks/deploy_scraper.yml
        directory: ./
