name: .NET CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  id-token: write

jobs:
  build_test:
    runs-on: ubuntu-latest
    env:
      working-directory: "Jobs.Aggregator"
      
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Install Global tools
      run: dotnet tool install --global Amazon.Lambda.Tools
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ env.working-directory }}
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{ env.working-directory }}
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{ env.working-directory }}

    - name: Package
      run: dotnet-lambda package
      working-directory: ${{ env.working-directory }}/Jobs.Aggregator.Local

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: eu-west-3
        role-to-assume: arn:aws:iam::326154968182:role/githubActions-iamRole

    - name: Deploy
      run: aws lambda update-function-code --function-name jobs-aggregator-lambda --region eu-west-3 --zip-file fileb://./bin/Release/netcoreapp3.1/Jobs.Aggregator.Local.zip
