name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      working-directory: "jobs_scaper"
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: gh cli auth
      run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
    
    - uses: actions/setup-dotnet@v1
    
    - name: Install GitVersion
      run: git fetch --unshallow && dotnet tool install --global GitVersion.Tool
    
    - name: Get semver
      id: semver
      run: echo "SEMVER=$(dotnet gitversion | jq -r '.FullSemVer')" >> $GITHUB_ENV
    
    - name: Restore dependencies
      run: go get ./...
      working-directory: ${{ env.working-directory }}

    - name: Build linux arm64
      run: go build -o jobs_scraper_${{ env.SEMVER }}_linux_arm64 ./entrypoints/sqs_worker
      env:
        GOOS: linux
        GOARCH: arm64
        
    - uses: actions/upload-artifact@v2
      with:
        name: client
        path: jobs_scraper_${{ env.SEMVER }}_linux_arm64
