name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      working-directory: "jobs_scaper"
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    
    - name: Restore dependencies
      run: go get ./...
      working-directory: ${{ env.working-directory }}

    - name: Build
      run: go build -v ./...
      working-directory: ${{ env.working-directory }}
