name: SCraping

on:
  schedule:
    - cron: "0 0 * * *"
  # Allow running manually
  workflow_dispatch:

jobs:

  scrape:
    name: "Scrap all sites"
    runs-on: "ubuntu-latest"
    env:
      working-directory: "jobs_scaper"
    
    steps:
      - uses: "actions/checkout@v2"
      
      - uses: actions/setup-go@v1
        with:
           go-version: '1.15.12'
           
      - name: "Debug"
        run: ls
      
      - name: "Restore dependencies"
        run: cd jobs_scraper && go get ./...
        working-directory: ${{ env.working-directory }}
        
      - name: "Run"
        run: cd jobs_scraper && go run ./entrypoints/single/
        working-directory: ${{ env.working-directory }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          IAM_ROLE: ${{ secrets.SCRAPER_IAM_ROLE }}
          RESULTS_BUCKET_NAME: ${{ secrets.SCRAPER_RESULTS_BUCKET_NAME }}
          SNS_TOPIC_DESTINATION_ARN: ${{ secrets.SCRAPER_RESULTS_BUCKET_NAME }}
